---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default
data:
  default.yaml: |-
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: ${org.revo.env.services.gateway.url}/auth/.well-known/jwks.json
      rabbitmq:
        username: zhowcpsz
        password: YU5WOYbSz901SccQxg6MrrxOSeYLSuSA
        host: mosquito.rmq.cloudamqp.com
        virtual-host: zhowcpsz
    management:
      endpoints:
        web:
          exposure:
            include: ["*"]
      endpoint:
        health:
          show-details: always
    info:
      app:
        name: ${spring.application.name}
    logging:
      file: /tmp/${spring.application.name}.log
      level:
        org.springframework: debug
    org:
      revo:
        env:
          buckets:
            video:
              accessible: false
              domain-name: ''
              name: asrevo-video
            ts:
              accessible: false
              domain-name: ''
              name: asrevo-ts
            thumb:
              accessible: true
              domain-name: ''
              name: asrevo-thumb
          services:
            gateway:
              name: gateway
              url: http://35.239.97.9
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ffmpeg
data:
  ffmpeg.yaml: |-
    spring:
      cloud:
        stream:
          bindings:
            ffmpeg_queue:
              destination: ffmpeg.queue
              group: s1
              contentType: application/json
            ffmpeg_converter_pop:
              destination: ffmpeg.converter
              group: s1
              contentType: application/json
            ffmpeg_converter_push:
              destination: ffmpeg.converter
              group: s1
              contentType: application/json
            ffmpeg_hls_push:
              destination: ffmpeg.hls
              group: s1
              contentType: application/json
            tube_info:
              destination: tube.info
              group: s1
              contentType: application/json
            ffmpeg_hls_pop:
              destination: ffmpeg.hls
              group: s1
              contentType: application/json
            tube_hls:
              destination: tube.hls
              group: s1
              contentType: application/json
          rabbit:
            bindings:
              ffmpeg_converter_pop:
                consumer:
                  max-priority: 20
                  concurrency: 1
                  maxConcurrency: 1
                  maxAttempts: 0
    logo: asrevo
    server:
      port: 8084
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader
rules:
- apiGroups: [""]
  resources: ["routes","pods","pods/log","pods/status","services","services/proxy","configmaps","endpoints","secrets","serviceaccounts","namespaces","namespaces/status","resourcequotas/status","events","bindings","replicationcontrollers","persistentvolumeclaims"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg
spec:
  selector:
    matchLabels:
      run: ffmpeg
  replicas: 1
  template:
    metadata:
      labels:
        run: ffmpeg
    spec:
      containers:
      - name: ffmpeg
        image: ashraf1abdelrasool/ffmpeg:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: ffmpeg
  labels:
    run: ffmpeg
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8084
  type: NodePort
  selector:
    run: ffmpeg
