spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${org.revo.env.services.auth.url}/auth/.well-known/jwks.json
  rabbitmq:
    username: zhowcpsz
    password: YU5WOYbSz901SccQxg6MrrxOSeYLSuSA
    host: mosquito.rmq.cloudamqp.com
    virtual-host: zhowcpsz
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    health:
      show-details: always
info:
  app:
    name: ${spring.application.name}
logging:
  file: /tmp/${spring.application.name}.log
  level:
    org.springframework: debug
org:
  revo:
    env:
      buckets:
        video:
          accessible: false
          domain-name: ''
          name: asrevo-video
        ts:
          accessible: false
          domain-name: ''
          name: asrevo-ts
        thumb:
          accessible: true
          domain-name: ''
          name: asrevo-thumb
      services:
        auth:
          name: auth
          url: http://localhost:9999
        tube:
          name: tube
          url: http://localhost:8081
        file:
          name: file
          url: http://localhost:8082
        feedback:
          name: feedback
          url: http://localhost:8083
        ffmpeg:
          name: ffmpeg
          url: http://localhost:8084
        gateway:
          name: gateway
          url: http://localhost:8080