---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default
data:
  default.yaml: |-
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: ${org.revo.env.services.gateway.url}/auth/.well-known/jwks.json
      rabbitmq:
        username: nwxkdlml
        password: cd9LnYXkcVzbzrBSYCDixZD3howw_k-O
        host: rhino.rmq.cloudamqp.com
        virtual-host: nwxkdlml
    management:
      endpoints:
        web:
          exposure:
            include: ["*"]
      endpoint:
        health:
          show-details: always
    info:
      app:
        name: ${spring.application.name}
    logging:
      file: /tmp/${spring.application.name}.log
      level:
        org.springframework: debug
    org:
      revo:
        env:
          buckets:
            video:
              accessible: false
              domain-name: ''
              name: asrevo-video
            ts:
              accessible: false
              domain-name: ''
              name: asrevo-ts
            thumb:
              accessible: true
              domain-name: ''
              name: asrevo-thumb
          services:
            gateway:
              name: gateway
              url: http://35.238.48.181
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
data:
  auth.yaml: |-
    spring:
      session:
        store-type: redis
      data:
        mongodb:
          database: CloudFoundry_jotgo8n0_o3nspm3g
          port: 63683
          password: AzyK1TQ2552raJO_-PCLdZIw6ZBetGb4
          username: CloudFoundry_jotgo8n0_o3nspm3g_bpifhjla
          host: ds163683.mlab.com
      redis:
        host: redis-16036.c93.us-east-1-3.ec2.cloud.redislabs.com
        password: wu3GgQInVUnTMfanU2SkIeUBHJqgnLaY
        port: 16036
    server:
      port: 9999
      servlet:
        context-path: /auth
        session:
          tracking-modes: cookie
      use-forward-headers: true
      tomcat:
        protocol-header: X-Forwarded-Proto
        remote-ip-header: X-Forwarded-For
        port-header: X-Forwarded-Port
        protocol-header-https-value: https
    org:
      revo:
        env:
          users:
          - id: 5bfd3df1ad8ce6617f9bf635
            email: ashraf1abdelrasool@gmail.com
            enable: true
            imageUrl: /assets/images/a5.jpg
            info: this is sample info about me you are welcome
            locked: true
            name: ashraf
            password: "{bcrypt}$2a$10$rPUJCZ6TmrrmDmHuIJptm.UIxsUcGm/WegmuwNfXE4eibF/kOEwWu"
            phone: 1120266849
            type: 111
          baseClients:
          - id: 5cd7294e9aad58282629eead
            name: revo
            clientId: revo
            userId: 5bfd3df1ad8ce6617f9bf635
            clientSecret: "{bcrypt}$2a$10$rPUJCZ6TmrrmDmHuIJptm.UIxsUcGm/WegmuwNfXE4eibF/kOEwWu"
            authorizedGrantTypes: "authorization_code"
            registeredRedirectUris: ${org.revo.env.services.gateway.url}/login/oauth2/code/login-client
            scope:
            - "read"
            - "write"
            autoApproveScopes: "read"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tube
data:
  tube.yaml: |-
    spring:
      data:
        mongodb:
          database: CloudFoundry_jotgo8n0_9b995k1v
          port: 63683
          password: 0qnrjUSJ4PkQoga0A6W-NpJ85k1BHGvm
          username: CloudFoundry_jotgo8n0_9b995k1v_hqpr23r7
          host: ds163683.mlab.com
      cloud:
        stream:
          bindings:
            asrevo_new_video:
              destination: asrevo.new.video
              group: s1
              contentType: application/json
            asrevo_hls_impl:
              destination: asrevo.hls.impl
              group: s1
              contentType: application/json
    server:
      port: 8081
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
data:
  gateway.yaml: |-
    spring:
      redis:
        host: redis-11283.c8.us-east-1-3.ec2.cloud.redislabs.com
        password: OTsAwaP3t11v3Z20FU2c6xioskDhDPxX
        port: 11283
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
              filters:
              - PreserveHostHeader
              - StripPrefix=1
              include-expression: (!serviceId.equals("auth")&&!serviceId.equals("gateway")&&!serviceId.equals("kubernetes"))
              url-expression: "'http://'+serviceId"
          routes:
          - id: auth
            uri: "http://auth"
            predicates:
            - Path=/auth/**
            filters:
            - PreserveHostHeader
      security:
        oauth2:
          client:
            registration:
              login-client:
                provider: auth
                client-id: revo
                client-secret: revo
                authorization-grant-type: authorization_code
                redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
                scope: read
            provider:
              auth:
                authorization-uri: ${org.revo.env.services.gateway.url}/auth/oauth/authorize
                token-uri: ${org.revo.env.services.gateway.url}/auth/oauth/token
                user-info-uri: ${org.revo.env.services.gateway.url}/auth/user
                user-name-attribute: sub
                jwk-set-uri: ${org.revo.env.services.gateway.url}/auth/.well-known/jwks.json
    server:
      port: 8080
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader
rules:
- apiGroups: [""]
  resources: ["routes","pods","pods/log","pods/status","services","services/proxy","configmaps","endpoints","secrets","serviceaccounts","namespaces","namespaces/status","resourcequotas/status","events","bindings","replicationcontrollers","persistentvolumeclaims"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""