---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default
data:
  default.yaml: |-
    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              jwk-set-uri: ${org.revo.env.services.gateway.url}/auth/.well-known/jwks.json
      rabbitmq:
        username: zhowcpsz
        password: YU5WOYbSz901SccQxg6MrrxOSeYLSuSA
        host: mosquito.rmq.cloudamqp.com
        virtual-host: zhowcpsz
    management:
      endpoints:
        web:
          exposure:
            include: ["*"]
      endpoint:
        health:
          show-details: always
    info:
      app:
        name: ${spring.application.name}
    logging:
      file: /tmp/${spring.application.name}.log
      level:
        org.springframework: debug
    org:
      revo:
        env:
          buckets:
            video:
              accessible: false
              domain-name: ''
              name: asrevo-video
            ts:
              accessible: false
              domain-name: ''
              name: asrevo-ts
            thumb:
              accessible: true
              domain-name: ''
              name: asrevo-thumb
          services:
            gateway:
              name: gateway
              url: http://35.193.181.79
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
data:
  auth.yaml: |-
    spring:
      session:
        store-type: redis
      data:
        mongodb:
          database: CloudFoundry_jotgo8n0_o3nspm3g
          port: 63683
          password: AzyK1TQ2552raJO_-PCLdZIw6ZBetGb4
          username: CloudFoundry_jotgo8n0_o3nspm3g_bpifhjla
          host: ds163683.mlab.com
      redis:
        host: redis-16036.c93.us-east-1-3.ec2.cloud.redislabs.com
        password: wu3GgQInVUnTMfanU2SkIeUBHJqgnLaY
        port: 16036
    server:
      port: 9999
      servlet:
        context-path: /auth
      use-forward-headers: true
      tomcat:
        protocol-header: X-Forwarded-Proto
        remote-ip-header: X-Forwarded-For
        port-header: X-Forwarded-Port
        protocol-header-https-value: https
    org:
      revo:
        env:
          users:
          - email: ashraf1abdelrasool@gmail.com
            enable: true
            id: 5bfd3df1ad8ce6617f9bf635
            imageUrl: /assets/images/a5.jpg
            info: this is sample info about me you are welcome
            locked: true
            name: ashraf
            password: "{bcrypt}$2a$10$rPUJCZ6TmrrmDmHuIJptm.UIxsUcGm/WegmuwNfXE4eibF/kOEwWu"
            phone: 1120266849
            type: 111
          baseClients:
          - name: revo
            clientId: revo
            userId: 5bfd3df1ad8ce6617f9bf635
            clientSecret: "{bcrypt}$2a$10$rPUJCZ6TmrrmDmHuIJptm.UIxsUcGm/WegmuwNfXE4eibF/kOEwWu"
            authorizedGrantTypes: "authorization_code"
            registeredRedirectUris: "https://asrevo.me"
            scope:
            - "read"
            - "write"
            autoApproveScopes: "read"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader
rules:
- apiGroups: [""]
  resources: ["routes","pods","pods/log","pods/status","services","services/proxy","configmaps","endpoints","secrets","serviceaccounts","namespaces","namespaces/status","resourcequotas/status","events","bindings","replicationcontrollers","persistentvolumeclaims"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader
roleRef:
  kind: Role
  name: reader
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      run: auth
  replicas: 1
  template:
    metadata:
      labels:
        run: auth
    spec:
      containers:
      - name: auth
        image: ashraf1abdelrasool/auth:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    run: auth
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9999
  type: LoadBalancer
  selector:
    run: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      run: ui
  replicas: 1
  template:
    metadata:
      labels:
        run: ui
    spec:
      containers:
      - name: ui
        image: ashraf1abdelrasool/ui:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    run: ui
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    run: ui
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
spec:
  rules:
  - http:
      paths:
      - path: /auth/?(.*)
        backend:
          serviceName: auth
          servicePort: 80
      - path: /?(.*)
        backend:
          serviceName: ui
          servicePort: 80