spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/auth/.well-known/jwks.json
  rabbitmq:
    username: zhowcpsz
    password: YU5WOYbSz901SccQxg6MrrxOSeYLSuSA
    host: mosquito.rmq.cloudamqp.com
    virtual-host: zhowcpsz
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    health:
      show-details: always
info:
  app:
    name: ${spring.application.name}
logging:
  file: /tmp/${spring.application.name}.log
  level:
    org.springframework: debug
org:
  revo:
    env:
      buckets:
        video:
          accessible: false
          domain-name: ''
          name: asrevo-video
        ts:
          accessible: false
          domain-name: ''
          name: asrevo-ts
        thumb:
          accessible: true
          domain-name: ''
          name: asrevo-thumb