spring:
  session:
    store-type: redis
  data:
    mongodb:
      database: CloudFoundry_jotgo8n0_o3nspm3g
      port: 63683
      password: AzyK1TQ2552raJO_-PCLdZIw6ZBetGb4
      username: CloudFoundry_jotgo8n0_o3nspm3g_bpifhjla
      host: ds163683.mlab.com
  redis:
    host: redis-16036.c93.us-east-1-3.ec2.cloud.redislabs.com
    password: wu3GgQInVUnTMfanU2SkIeUBHJqgnLaY
    port: 16036
server:
  port: 9999
  servlet:
    context-path: /auth
  use-forward-headers: true
  tomcat:
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For
    port-header: X-Forwarded-Port
    protocol-header-https-value: https
org:
  revo:
    env:
      users:
      - id: 5bfd3df1ad8ce6617f9bf635
        email: ashraf1abdelrasool@gmail.com
        enable: true
        imageUrl: /assets/images/a5.jpg
        info: this is sample info about me you are welcome
        locked: true
        name: ashraf
        password: "{bcrypt}$2a$10$rPUJCZ6TmrrmDmHuIJptm.UIxsUcGm/WegmuwNfXE4eibF/kOEwWu"
        phone: 1120266849
        type: 111
      baseClients:
      - id: 5cd7294e9aad58282629eead
        name: revo
        clientId: revo
        userId: 5bfd3df1ad8ce6617f9bf635
        clientSecret: "{bcrypt}$2a$10$rPUJCZ6TmrrmDmHuIJptm.UIxsUcGm/WegmuwNfXE4eibF/kOEwWu"
        authorizedGrantTypes: "authorization_code"
        registeredRedirectUris: ${org.revo.env.services.gateway.url}/login/oauth2/code/login-client
        scope:
        - "read"
        - "write"
        autoApproveScopes: "read"
