spring:
  data:
    mongodb:
      database: CloudFoundry_jotgo8n0_9b995k1v
      port: 63683
      password: 0qnrjUSJ4PkQoga0A6W-NpJ85k1BHGvm
      username: CloudFoundry_jotgo8n0_9b995k1v_hqpr23r7
      host: ds163683.mlab.com
  cloud:
    stream:
      bindings:
        asrevo_new_video:
          destination: asrevo.new.video
          group: s1
          contentType: application/json
        asrevo_hls_impl:
          destination: asrevo.hls.impl
          group: s1
          contentType: application/json
server:
  port: 8081
