spring:
  data:
    mongodb:
      database: CloudFoundry_jotgo8n0_9b995k1v
      port: 63683
      password: 0qnrjUSJ4PkQoga0A6W-NpJ85k1BHGvm
      username: CloudFoundry_jotgo8n0_9b995k1v_hqpr23r7
      host: ds163683.mlab.com
  cloud:
    stream:
      bindings:
        tube_hls:
          destination: tube.hls
          group: s1
          contentType: application/json
        tube_info:
          destination: tube.info
          group: s1
          contentType: application/json
        tube_store:
          destination: tube.store
          group: s1
          contentType: application/json
        ffmpeg_queue:
          destination: ffmpeg.queue
          group: s1
          contentType: application/json
        feedback_index:
          destination: feedback.index
          group: s1
          contentType: application/json
        file_queue:
          destination: file.queue
          group: s1
          contentType: application/json
        torrent_queue:
          destination: torrent.queue
          group: s1
          contentType: application/json
server:
  port: 8081
