spring:
  profiles: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${org.revo.env.services.auth.url}/.well-known/jwks.json
  rabbitmq:
    username: zhowcpsz
    password: YU5WOYbSz901SccQxg6MrrxOSeYLSuSA
    host: mosquito.rmq.cloudamqp.com
    virtual-host: zhowcpsz
management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  endpoint:
    health:
      show-details: always
info:
  app:
    name: ${spring.application.name}
logging:
  file: /tmp/${spring.application.name}.log
  level:
    org.springframework: debug
org:
  revo:
    env:
      buckets:
        video:
          accessible: false
          domain-name: ''
          name: asrevo-video
        ts:
          accessible: false
          domain-name: ''
          name: asrevo-ts
        thumb:
          accessible: true
          domain-name: ''
          name: asrevo-thumb
      services:
        auth:
          name: auth
          url: http://localhost:9999/auth
        tube:
          name: tube
          url: http://localhost:8081
        file:
          name: file
          url: http://localhost:8082
        feedback:
          name: feedback
          url: http://localhost:8083
        ffmpeg:
          name: ffmpeg
          url: http://localhost:8084
        gateway:
          name: gateway
          url: http://localhost:8080
---
spring:
  profiles: kubernetes
org:
  revo:
    env:
      services:
        auth:
          name: auth
          url: ${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}
        tube:
          name: tube
          url: ${TUBE_SERVICE_HOST}:${TUBE_SERVICE_PORT}
        file:
          name: file
          url: ${FILE_SERVICE_HOST}:${FILE_SERVICE_PORT}
        feedback:
          name: feedback
          url: ${FEEDBACK_SERVICE_HOST}:${FEEDBACK_SERVICE_PORT}
        ffmpeg:
          name: ffmpeg
          url: ${FFMPEG_SERVICE_HOST}:${FFMPEG_SERVICE_PORT}
        gateway:
          name: gateway
          url: ${GATEWAY_SERVICE_HOST}:${GATEWAY_SERVICE_PORT}