spring:
  cloud:
    stream:
      bindings:
        ffmpeg_queue:
          destination: ffmpeg.queue
          group: s1
          contentType: application/json
        ffmpeg_converter_pop:
          destination: ffmpeg.converter
          group: s1
          contentType: application/json
        ffmpeg_converter_push:
          destination: ffmpeg.converter
          group: s1
          contentType: application/json
        ffmpeg_hls_push:
          destination: ffmpeg.hls
          group: s1
          contentType: application/json
        tube_info:
          destination: tube.info
          group: s1
          contentType: application/json
        ffmpeg_hls_pop:
          destination: ffmpeg.hls
          group: s1
          contentType: application/json
        tube_hls:
          destination: tube.hls
          group: s1
          contentType: application/json
      rabbit:
        bindings:
          ffmpeg_converter_pop:
            consumer:
              max-priority: 20
              concurrency: 1
              maxConcurrency: 1
              maxAttempts: 0
logo: asrevo
server:
  port: 8084
